services:
  - type: web
    name: youtube-downloader-backend
    env: node
    rootDir: backend
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: PORT
        value: 4000
